CREATE TABLE curators (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    password text NOT NULL,
    full_name text NOT NULL,
    profile_img_link text,
    profile_description text,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);