INSERT INTO subscribers 
(phone_number, curator_id)
VALUES
('917-344-9404', 1),
('917-344-9404', 2),
('test number', 2),
('deleted number', 3);

/*

CREATE TABLE subscribers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone_number text NOT NULL,
    curator_id INTEGER 
        REFERENCES curators(id) ON DELETE CASCADE NOT NULL
);

*/