INSERT INTO messages 
(content, curator_id, scheduled)
VALUES
('Donate to Lorem Ipsum', 
'1', 
'2020-06-18T09:00'),

('We won today, get some rest!', 
'1', 
'2020-06-26T23:30'),

('Read this!', 
'1', 
'2020-06-18T11:00'),

('Take care of yourself from away', 
'1', 
'2020-06-22T09:00'),

('Hello World', 
'2', 
'2020-06-26T09:00'),

('What to wear during protest today', 
'1', 
'2020-06-26T09:00'),

('Not supposed to see this if logged in correctly', 
'2', 
'2020-06-26T09:00'),

('Delete user test', 
'7', 
'2020-06-26T09:00');






/*

 messages: [
          {
              scheduled: "2020-06-18T09:00",
              content: "Donate to Lorem Ipsum",
              id: 1,
              curator_id: 1,
          },
          {
            scheduled: "2020-06-26T23:30",
            content: "We won today, get some rest!",
            id: 6,
            curator_id: 1,
          },
          {
            scheduled: "2020-06-18T11:00",
            content: "Read this",
            id: 4,
            curator_id: 1,
        },
        {
            scheduled: "2020-06-22T09:00",
            content: "Take Care of yourself during a revolution",
            id: 2,
            curator_id: 1,
        },
        {
            scheduled: "2020-06-26T09:00",
            content: "What to wear during today's protest",
            id: 3,
            curator_id: 1,
        },
        {
          scheduled: "2020-06-26T09:00",
          content: "Hello World",
          id: 5,
          curator_id: 2,
      },
      ],

    */
/*

CREATE TABLE messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    curator_id INTEGER 
        REFERENCES curators(id) ON DELETE CASCADE NOT NULL,
    scheduled TIMESTAMPTZ NOT NULL,
    date_modified TIMESTAMPTZ NOT NULL DEFAULT now()
);
*/